# Generated by Django 2.2 on 2024-01-16 15:26

import django.core.validators
from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': '이미 같은 제목의 게시글이 존재합니다'}, max_length=50, unique=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10, '10자 이상 입력해주세요'), posts.validators.validate_symbols])),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
    ]
